from os import listdir,makedirs,walk
from os.path import join,isdir,dirname,split,abspath,exists,basename
import pandas as pd
from glob import glob
from shutil import copyfile
from snakemake.utils import validate
import pandas as pd 
import numpy as np

configfile: 'config/config.yml'
validate(config, "schemas/config.schema.yml")

subject_id = config['subject_prefix']+'{subject}'

config['out_dir'] = config['bids_dir']
config['participants_tsv'] = join(config['bids_dir'], 'participants_run.tsv')
config['subject_seega_scene'] = join(config['bids_dir'], config['subject_seega_scene'])

if exists(config['participants_tsv']):
    df = pd.read_table(config['participants_tsv'], dtype = str, header=0)
    subjects=df.participant_id.to_list()
    if 'sub-P' in subjects[0]:
        subjects = [ s.strip('sub-P') for s in subjects]
    elif 'sub-' in subjects[0]:
        subjects = [x.split('-')[1] for x in subjects]
    else:
        subjects = [ str(s).zfill(3) for s in subjects]
else:
    subjects = [x.split('-')[1].strip(config['subject_prefix']) for x in listdir(join(config['bids_dir'],'bids')) if isdir(join(config['bids_dir'], 'bids',x)) and x.startswith('sub')]

#this include is for the bids() function, and 
#and any other global function declarations
include: 'rules/common.smk'

final_outputs = []

def get_age_appropriate_template_name(subject):
    if not exists(join(config['out_dir'], 'bids','participants.tsv')):
        return config['adult_template']['name']
    else:
        df = pd.read_table(join(config['out_dir'], 'bids','participants.tsv'), dtype = str, header=0)
        if 'sub-'+subject[0] in df.participant_id.to_list():
            age=int(df[df['participant_id']=='sub-'+subject[0]]['age'])
            if age <18 and age > 13:
                return config['MNIPediatricAsymCohort6']['name']
            elif age <=13 and age > 7:
                return config['MNIPediatricAsymCohort4']['name']
            elif age <=7:
                return config['MNIPediatricAsymCohort2']['name']
            else:
                return config['adult_template']['name']
        else:
            return config['adult_template']['name']


if config['fmriprep']['run']:
    include: 'rules/fmriprep.smk'
    if not exists(join(config['out_dir'], 'derivatives', 'fmriprep')):
       makedirs(join(config['out_dir'], 'derivatives', 'fmriprep'))

if config['fastsurfer']['run']:
    include: 'rules/fastsurfer.smk'

if config['hippunfold']['run']:
    include: 'rules/hippunfold.smk'

#include: "rules/registration.smk"
#include: "rules/visqc.smk"
#include: "rules/segmentation.smk"

#if config['seeg_contacts']['present']:
#    include: 'rules/electrodes.smk'

rule all:
        input:
            final_outputs
